services:
  bolt:
    image: registry.srvr.site/bolt-ai:latest
    container_name: bolt
    env_file: 
      - ./stack.env
    networks:
      srvr:
        ipv4_address: 10.10.10.23
    command: pnpm run dockerstart

networks:
  srvr:
    external: true
