services:
  bolt:
    image: registry.srvr.site/bolt-ai:latest
    container_name: bolt
    env_file: "stack.env"
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
      - PORT=5173
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    networks:
      srvr:
        ipv4_address: 10.10.10.23
    command: pnpm run dockerstart

networks:
  srvr:
    external: true
