name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: srvr

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        sudo docker build \
          --target bolt-ai-production \
          --network host \
          -t registry.srvr.site/bolt-ai:latest \
          -f Dockerfile .

    - name: Push Docker image
      run: |
        sudo docker push registry.srvr.site/bolt-ai:latest

    - name: Trigger Portainer Webhook
      run: |
        curl -X POST https://portainer.srvr.site/api/stacks/webhooks/4a9e18b0-57c4-42fa-819b-7a7ecf7e9084
  
